### PR TITLE
Fix arctitecture tj

### LINKED ISSUE #7: Post Request User
As a dev I want the correct user info to be accessed using a post request if the user inputs their correct credentials.

### PR DESCRIPTION
**Pull request by taylorjohnson141**
## Types of changes 

- [] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
## Checklist:  
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

What’s this PR do?
This PR helps adds the post request for a user login

Where should the reviewer start?
app.js for post request 
How should this be manually tested?

npm test add correct user credientials should see user data when press submit

Any background context you want to provide?
Will add login button next
What are the relevant tickets?
closes #7 
Screenshots (if appropriate)
Questions:

### CODE REVIEW

File: src/App.js [hunk 1]
```diff
@@ -9,20 +9,42 @@ class App extends Component{
...
-    if(this.state.isLogin){
-      return <Login/>
+    if(this.state.isLoginPage){
+      return <Login addUser ={this.addUser} />
     }
     return (
     <React.Fragment>
     <Header changeLogin = {this.changeLogin} />
-   <Movies/>
+   <Movies userLoggedIn = {this.state.userLoggedIn}/>
```
Comment (chadrick-d-dev) [inline src/App.js:47]: Why did we reassign the value of userLoggedIn here?

File: src/Login.js [hunk 2]
```diff
@@ -18,9 +18,12 @@ class Login extends Component{
   handleSubmit = (event) =>{
     console.log(this.state)
     event.preventDefault();
-    if(this.state.email === 'sam@turing.io' && String(this.state.password) ==='123456' )
-    console.log('works')
+    if(this.state.email === 'sam@turing.io' && String(this.state.password) ==='123456' ){
+      this.props.addUser(this.state)
```
Comment (chadrick-d-dev) [inline src/Login.js:22]: this.props.addUser is carried into login through props. A method from a parent class can be carried through props to a child class.

**Review by chadrick-d-dev — APPROVED** [review]
